### ISSUE TITLE
Cache unit test improvement

### ISSUE THREAD

**Issue by DavidGruzman** [ImpalaToGo/ImpalaToGo#39]
We have to implement the following test scenario. It should be run on different combination of conditions.
Main stability test

variatopn A.

1. Long test which includes:
a. 20 requesting threads. 
b. 100M operations per thread
c. 90% regular request to existing files
d. 9% requests to non existing files.
e. 1% of cacnels
f. small random delay in the code to simulate different read speed. 
g. Each 100K operation print of the heap status: size, free space + free disk space. 

Statistics to be maintained and printed periodically:
1. Number of total requests
2. Number of cach hits
3. Number of cache misses
4. Number of cancels of active downloads
5. Number of direct reads (w/o chache)

This statistics will show us that cache is indeed tested.

The goal of the test to see that 
- no crashes
- stable memory and disk space

Condition A. 
Compiling code with release compilation. 

Condition B 
Ranning on single CPU machine

Condition C
Running on dual CPU machine

Condition D
Running with datasets of 10K files

Condition E
Running with datasets of 10 files

Condition F. 
Running with dataset bigger then cache size

Condition F. 
Running with dataset smaller then cache size

**Comment by elenaviter** [comment]
Remained part:
to check the solution with valgrind
