### ISSUE TITLE
Make cache path configurable

### ISSUE THREAD

**Issue by navado** [ImpalaToGo/ImpalaToGo#45]
Currently cache path is hardcoded to be **/var/cache/impalatogo**.
It should be possible to specify the path before startup in a configuration file.

**Comment by elenaviter** [comment]
This path is configurable via impalad option and if no option specified it will be set to var/cache/impalatogo

**Comment by navado** [comment]
2 questions:
1 - What's the option?
2- Is the directory created if not forund?

**Comment by DavidGruzman** [comment]
If dir not found impala crashes.

**Comment by elenaviter** [comment]
impalad startup options specific for cache layer are:
  - **cache_location** - specify the absolute path where the root cache will be managed by Impala.
If omitted, /var/cache/impalatogo is for defaults. If empty and **cache_mem_percent_of_available** is 0, 2 options: 
  > tachyon is configured : use tachyon as cache layer
  > no tachyon configured - use direct dfs work (no cache in between)

  - **cache_mem_percent_of_available** - percent of available memory on path specified with  **cache_location** that is allowed for Impala cache layer management. For more options, see above.

What about the cache location existence on Impala startup : should be decided should exist or we should create it (no shutdown if no configured cache exists). Please advice.

**Comment by navado** [comment]
I think the directory should be created while warning printed in the log.
