### ISSUE TITLE
Tachyon integration : scan range seek operation causes either file is not cached or query crash 

### ISSUE THREAD

**Issue by elenaviter** [ImpalaToGo/ImpalaToGo#50]
1. **Scan range "open" flow actions in regards to file:**
    - open file;
    - seek to offset

2. **What does it mean in Tachyon :**
    - when file is opened, the client receives the "in" stream which can be used for read;
    - "out" caching stream is created in background. This stream will be used to flush the data which will be read from dfs or from another worker (depends) - flush it into local temporary file.
Temp file is being written as the client reads using "in" stream he got from Tachyon.
    - So, Scan range opened file and 2 streams were created : "in" - for reading - and "out" - for temp file;
    - Immediately after "open", scan range does "seek". As designed, once detecting "seek" on its instream, Tachyon interrupts caching of the file (because caching is being done by consequential client reads, linear along the stream, no seek, no skip is possible).

3. **What happens for Impala as a client of scenario 1.**
    2 cases:
    - "seek" is invoked with offset which fits the current block size loaded in context of Tachyon in-stream.
         This will cause file caching cancellation. Query will succeed and will have valid result. 
         File will not be cached by Tachyon, next read will be again direct read.
    - "seek" is invoked with offset which exceeds current block size loaded in context of Tachyon in-stream.
       This will cause seek operation failure on Tachyon stream, no rewind. Query will fail. 
       Corresponding shell message: 
         
       ```bash
       Error seeking to 67108864 in file: tachyon://ec2-54-159-3-242.compute-1.amazonaws.com:19998/tpcds1/web_sales/web_sales.dat 
       Error(255): Unknown error 255
       ```

**Comment by DavidGruzman** [comment]
I think we should report the issue to  Tachyon

**Comment by elenaviter** [comment]
This behavior is "as designed" for Tachyon. Desired behavior is tuned up by Tachyon client, of you want seek you need to be sure the file is cached locally till the moment you are going to rewind its stream.
