### ISSUE TITLE
Configure data access mode alternatives

### ISSUE THREAD

**Issue by elenaviter** [ImpalaToGo/ImpalaToGo#58]
ImpalaToGo supports 3 ways of data access at this stage.
Data access level should be configurable during cluster setup.
Relevant configuration details below:
  -  via **/etc/default/impala**, by editing **cache_location** and **cache_mem_percent_of_available** IMPALA_SERVER_ARGS 
  - in case if Tachyon is in use, hdfs-site.xml should be also edited as stated by     
https://github.com/ImpalaToGo/ImpalaToGo/wiki/To-run-ImpalaToGo-over-Tachyon

    Levels and configuration:
    - **pass through (no data cached).** 
          > Corresponding configuration of **/etc/default/impala**:
         ```bash
                -cache_location= \
                -cache_mem_percent_of_available=0 \       
         ```

   - **built-in c++ cache**.
          > Corresponding configuration of **/etc/default/impala**:
         ```bash
                -cache_location=/var/cache/impalatogo \
                -cache_mem_percent_of_available=85 \       
         ```

   - **Tachyon  serves cache layer** 
          > Corresponding configuration of **/etc/default/impala**:
         ```bash
                -cache_location= \
                -cache_mem_percent_of_available=0 \       
         ```

         Configuration in **hdfs-site.xml**:
         ```xml
         <property>
           <name>fs.defaultFS</name>
           <value>tachyon://host_running_tachyon_master_DNS:19998</value>
         </property>
         <property>
           <name>fs.default.name</name>
           <value>tachyon://host_running_tachyon_master_DNS:19998</value>
           <description>The name of the default file system.  A URI whose scheme and authority determine the  FileSystem implementation.</description>
         </property>
         <property>
           <name>fs.tachyon.impl</name>
           <value>tachyon.hadoop.TFS</value>
         </property>
         ```

**Comment by navado** [comment]
So the solution is to add configuration template for each way and switch accordingly?

**Comment by navado** [comment]
https://s3.amazonaws.com/impala-to-go/Impala2go-cluster-cdh-5.5.template
