### ISSUE TITLE
 Tachyon dependency : use upstream sources

### ISSUE THREAD

**Issue by elenaviter** [ImpalaToGo/ImpalaToGo#61]
As all local fixes were moved to Tachyon upstream, for Tachyon build we should use sources from     upstream https://github.com/amplab/tachyon. Local build is required because we need to edit Tachyon's pom for several reasons: 
  - Tachyon's native pom does not contain extra dependencies required for work with s3, so we need to add these dependencies:

  ```xml
     <dependency>
       <groupId>net.java.dev.jets3t</groupId>
       <artifactId>jets3t</artifactId>
       <version>0.9.0</version>
       <exclusions>
         <exclusion>
           <groupId>commons-codec</groupId>
           <artifactId>commons-codec</artifactId>
           <!-- <version>1.3</version> -->
         </exclusion>
       </exclusions>
     </dependency>
  ```
  - we need to build for current CDH, so we change hadoop.version : 

  ```xml
    ...
    <properties>
      <hadoop.version>2.6.0-cdh5.5.0-SNAPSHOT</hadoop.version>
    ...
    </properties>
  ```

**Comment by navado** [comment]
We have Hadoop version in environment when building.
Suggest using ${env.HADOOP_VERSION} instead hard-coded value

As for the repo, there is a work started for the migration, we can move to that direction. 
See https://github.com/ImpalaToGo/i2g-repo-manifests for reference

**Comment by navado** [comment]
branch generic-tachyon
