### ISSUE TITLE
Handling new dependencies in Impala

### ISSUE THREAD

**Issue by elenaviter** [ImpalaToGo/ImpalaToGo#63]
Deployment and installation changes
   - add deployment and installation of impala **www** folder with content (for impala web app)
   - add new dependency - ```json-simple-1.1.1.jar ```   into impala CLASSPATH  (**/usr/bin/impalad**)

**Comment by navado** [comment]
i.e. update deploy.sh and install.sh ?

**Comment by elenaviter** [comment]
deploy and install are ok here, as they just deploy/install **all** frontend dependencies.
This change affects only **/usr/bin/impalad**

**Comment by elenaviter** [comment]
Done in new image
